name: todo_sqflite
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sqflite:
  provider:
  path:
  intl:

  bloc:
  flutter_bloc:
  sizer:
  fluttertoast:
  flutter_local_notifications: ^9.7.0
  timezone:



  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  state_notifier: ^0.7.2+1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  mockito: ^5.3.2


flutter:

  uses-material-design: true

  assets:
    - assets/


